# Generated by Django 5.0.1 on 2026-01-29 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malariaApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionmodel',
            name='confidence',
            field=models.FloatField(default=0.0),
        ),
    ]
